### ISSUE TITLE
[JOSS] no effective testing

### ISSUE THREAD

**Issue by dham** [gbertoldo/DEPP#6]
Part of openjournals/joss-reviews#1701

The code does not have an adequate testing arrangement. What is provided is one example, and a script which appears to only check that that one example executes without crashing. 

I would expect to see a suite of tests designed to show that the algorithm performs as expected for a variety of problems. As a user, I would expect to be able to establish from running the tests that the implementation is correct,  for example because a number of problems with known solutions are solved and the scripts test the correctness of the solutions. 

Ideally I would expect to see continuous integration testing in order to ensure that changes to the software do not break it. At a minimum I would expect a command which can be run to execute all the tests, and report which of these pass and fail.

**Comment by gbertoldo** [comment]
Hi, @dham and @HaoZeke, I think this issue is solved. There are two scripts within test/: one of them to check DEPP installation and another one for code verification. We also updated the Wiki documentation and the JOSS paper. We applied four test functions for code verification. These functions present different levels of difficulty to be optimized. They are also unimodal to ensure a unique answer when comparing numerical and analytical solutions. Since DEPP is a stochastic software, the solution will change from one run to another. However, numerical solutions must always agree with analytical one within the prescribed error tolerance. Instructions for code verification are given here: https://github.com/gbertoldo/DEPP/wiki/How-to-install-DEPP-on-Linux#code-verification.
